# Generated by Django 5.1.4 on 2025-05-16 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="设备名称")),
                (
                    "device_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="设备ID"
                    ),
                ),
                ("location", models.CharField(max_length=255, verbose_name="设备位置")),
                ("room_id", models.IntegerField(verbose_name="房间ID")),
                ("floor_id", models.IntegerField(verbose_name="楼层ID")),
                ("building_id", models.IntegerField(verbose_name="建筑ID")),
                (
                    "current_temp",
                    models.FloatField(default=25.0, verbose_name="当前温度"),
                ),
                ("set_temp", models.FloatField(default=25.0, verbose_name="设定温度")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "运行"),
                            ("stopped", "停止"),
                            ("fault", "故障"),
                        ],
                        default="stopped",
                        max_length=20,
                        verbose_name="运行状态",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("cooling", "制冷"),
                            ("heating", "制热"),
                            ("fan", "送风"),
                            ("dehumidify", "除湿"),
                        ],
                        default="cooling",
                        max_length=20,
                        verbose_name="运行模式",
                    ),
                ),
                (
                    "is_auto",
                    models.BooleanField(default=False, verbose_name="是否自动控制"),
                ),
                (
                    "running_time",
                    models.FloatField(default=0.0, verbose_name="运行时间(小时)"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="最后更新时间"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "设备",
                "verbose_name_plural": "设备管理",
            },
        ),
        migrations.CreateModel(
            name="DeviceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_temp", models.FloatField(verbose_name="当前温度")),
                ("set_temp", models.FloatField(verbose_name="设定温度")),
                ("status", models.CharField(max_length=20, verbose_name="运行状态")),
                ("mode", models.CharField(max_length=20, verbose_name="运行模式")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="记录时间"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="device.device",
                        verbose_name="设备",
                    ),
                ),
            ],
            options={
                "verbose_name": "设备状态记录",
                "verbose_name_plural": "设备状态历史",
                "ordering": ["-timestamp"],
            },
        ),
    ]
