# Generated by Django 5.1.4 on 2025-05-23 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = []
