# Generated by Django 5.1.4 on 2025-05-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="floor_number",
            field=models.IntegerField(verbose_name="楼层号"),
        ),
    ]
