# Generated by Django 5.1.4 on 2025-05-19 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0002_alter_device_floor_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="floor_number",
        ),
    ]
