# Generated by Django 5.1.4 on 2025-05-22 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0003_remove_device_floor_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="公司名称")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="公司编码"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="公司描述"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "公司",
                "verbose_name_plural": "公司管理",
            },
        ),
        migrations.AddField(
            model_name="device",
            name="fan_speed",
            field=models.IntegerField(
                choices=[
                    (0, "自动"),
                    (1, "高速"),
                    (2, "中速"),
                    (4, "低速"),
                    (6, "微风"),
                ],
                default=0,
                verbose_name="风速",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="mode",
            field=models.CharField(
                choices=[
                    ("auto", "自动"),
                    ("cooling", "制冷"),
                    ("heating", "制热"),
                    ("fan", "送风"),
                    ("dehumidify", "除湿"),
                ],
                default="cooling",
                max_length=20,
                verbose_name="运行模式",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="device.company",
                verbose_name="所属公司",
            ),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="部门名称")),
                ("code", models.CharField(max_length=50, verbose_name="部门编码")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="部门描述"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="device.company",
                        verbose_name="所属公司",
                    ),
                ),
            ],
            options={
                "verbose_name": "部门",
                "verbose_name_plural": "部门管理",
            },
        ),
        migrations.AddField(
            model_name="device",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="device.department",
                verbose_name="所属部门",
            ),
        ),
        migrations.CreateModel(
            name="DeviceAlarm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alarm_type",
                    models.CharField(max_length=50, verbose_name="报警类型"),
                ),
                (
                    "alarm_level",
                    models.CharField(
                        choices=[
                            ("low", "低级"),
                            ("medium", "中级"),
                            ("high", "高级"),
                            ("critical", "严重"),
                        ],
                        default="low",
                        max_length=20,
                        verbose_name="报警等级",
                    ),
                ),
                ("alarm_message", models.TextField(verbose_name="报警信息")),
                (
                    "is_handled",
                    models.BooleanField(default=False, verbose_name="是否处理"),
                ),
                (
                    "handled_by",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="处理人"
                    ),
                ),
                (
                    "handled_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="处理时间"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alarms",
                        to="device.device",
                        verbose_name="设备",
                    ),
                ),
            ],
            options={
                "verbose_name": "设备报警",
                "verbose_name_plural": "设备报警管理",
                "ordering": ["-create_time"],
            },
        ),
    ]
