# Generated by Django 5.1.4 on 2025-05-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0004_company_device_fan_speed_alter_device_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicestatus",
            name="fan_speed",
            field=models.IntegerField(default=0, verbose_name="风速"),
        ),
    ]
