# Generated by Django 5.1.4 on 2025-05-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0005_devicestatus_fan_speed"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="uuid",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="设备UUID",
            ),
        ),
    ]
