# Generated by Django 5.1.4 on 2025-05-22 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0006_device_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="is_auto",
        ),
        migrations.RemoveField(
            model_name="device",
            name="location",
        ),
    ]
