# Generated by Django 5.1.4 on 2025-05-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0007_remove_device_is_auto_remove_device_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="设备UUID"
                    ),
                ),
                ("topic", models.CharField(max_length=255, verbose_name="MQTT主题")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="主题描述"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "设备主题",
                "verbose_name_plural": "设备主题管理",
                "db_table": "device_topic",
                "ordering": ["-create_time"],
            },
        ),
    ]
