# Generated by Django 5.1.4 on 2025-05-22 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0008_devicetopic"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DeviceAlarm",
        ),
    ]
