# Generated by Django 5.1.4 on 2025-04-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sysuser",
            name="create_time",
            field=models.DateTimeField(null=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="sysuser",
            name="login_date",
            field=models.DateTimeField(null=True, verbose_name="最后登录时间"),
        ),
        migrations.AlterField(
            model_name="sysuser",
            name="update_time",
            field=models.DateTimeField(null=True, verbose_name="更新时间"),
        ),
    ]
