# Generated by Django 5.1.4 on 2025-05-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_sysuser_options_alter_sysuser_avatar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sysuser",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="userAvatar", verbose_name="用户头像"
            ),
        ),
    ]
