# Generated by Django 5.1.4 on 2025-05-16 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="批量命令名称")),
                (
                    "command_type",
                    models.CharField(max_length=50, verbose_name="命令类型"),
                ),
                (
                    "command_value",
                    models.CharField(max_length=255, verbose_name="命令值"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("executing", "执行中"),
                            ("completed", "已完成"),
                            ("failed", "执行失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "success_count",
                    models.IntegerField(default=0, verbose_name="成功数量"),
                ),
                ("fail_count", models.IntegerField(default=0, verbose_name="失败数量")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "target_devices",
                    models.ManyToManyField(
                        related_name="batch_commands",
                        to="device.device",
                        verbose_name="目标设备",
                    ),
                ),
            ],
            options={
                "verbose_name": "批量命令",
                "verbose_name_plural": "批量命令管理",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="ControlCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "command_type",
                    models.CharField(max_length=50, verbose_name="命令类型"),
                ),
                (
                    "command_value",
                    models.CharField(max_length=255, verbose_name="命令值"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("sent", "已发送"),
                            ("success", "执行成功"),
                            ("failed", "执行失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "execute_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="执行时间"
                    ),
                ),
                (
                    "result",
                    models.TextField(blank=True, null=True, verbose_name="执行结果"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="device.device",
                        verbose_name="设备",
                    ),
                ),
            ],
            options={
                "verbose_name": "控制命令",
                "verbose_name_plural": "控制命令管理",
                "ordering": ["-create_time"],
            },
        ),
    ]
